#!/bin/bash

##############################################
#                                            #
# Here is preload and settings block of code #
#                                            #
##############################################

# NOTICE:
#
# 0 - OFF | 1 - ON
#
# Dependencies are have indent

# daemon settings

loop="1" # set daemon loop - DO NOT CHANGE!

skip="sleep 0" # function of skipping - DO NOT CHANGE!

longwait="sleep 600" # quiz frequency in seconds - you can change it on your own

# daemon settings

# brightness settings

use_changing_brightness="0"

	oneshot_brightness="0"

	daemon_brightness="0"

	path_brightness="/sys/class/backlight/intel_backlight/brightness" # ATTENTION! You should change it on your own

	ac_brightness="12421" # ATTENTION! You should change it on your own

	battery_brightness="0" # ATTENTION! You should change it on your own

# brightness settings

# tray indicator settings

use_gtrayicon="0" # depends of gtrayicon package

# tray indicator settings

# notification settings

use_notify_send="0" # depends of notify-send package (libnotify-bin or notify-osd)

	use_notify_send_standalone="0"

	use_notify_send_with_gtrayicon="0"

# notification settings

# kernel settings

use_changing_kernel_params="0"

	use_smt_power_saving="0"

	use_mc_power_saving="0"

# kernel settings

# powertop settings

use_powertop="0" # depends of powertop package

# powertop settings

# modprobe settings

use_modprobe="0" # depends of modprobe package (kmod)

	use_changing_camera="0"

# modprobe settings

# wireless interface settings

use_wireless_powersaving="0"

	wireless_interface="wlp5s0" # ATTENTION! You should change it on your own

	use_iw_pm="0"

	use_iw_txpower="0"

		iw_default_txpower="16" # ATTENTION! You should change it on your own

			iw_set_default_txpower="auto" # ATTENTION! You should change it on your own

		iw_powersave_txpower="1" # ATTENTION! You should change it on your own

			iw_set_powersave_txpower="limit 100" # ATTENTION! You should change it on your own

	use_iwconfig_pm="0"

	use_iwconfig_txpower="0"

		iwconfig_default_txpower="16" # ATTENTION! You should change it on your own

			iwconfig_set_default_txpower="auto" # ATTENTION! You should change it on your own

		iwconfig_powersave_txpower="1" # ATTENTION! You should change it on your own

			iwconfig_set_powersave_txpower="1" # ATTENTION! You should change it on your own

# wireless interface settings

# rfkill settings

use_rfkill="0"

	use_changing_wifi="0"

		oneshot_wifi="0"

		daemon_wifi="0"

	use_changing_bluetooth="0"

		oneshot_bluetooth="0"

		daemon_bluetooth="0"

# rfkill settings

# ipv6 settings

use_changing_ipv6="0"

	use_sysctl="0"

# ipv6 settings

# scsi settings

use_changing_scsi="0"

	number_of_scsi_host="0" # ATTENTION! You should change it on your own

	ac_scsi_host="max_performance"

	battery_scsi_host="min_power"

# scsi settings

# cpu governor settings

use_changing_governor="0"

	use_cpufreq="0" # depends of cpufreq-utils package

	number_of_cores="4" # ATTENTION! You should change it on your own

	battery_governor="powersave" # ATTENTION! You should change it on your own

	ac_governor="performance" # ATTENTION! You should change it on your own

# cpu governor settings

# pcie settings

use_changing_pcie="0"

# pcie settings

# hdparm settings

use_hdparm="0" # depends of hdparm package

	hard_disk="/dev/sda" # ATTENTION! You should change it on your own

# hdparm settings

# cdrom hal polling settings

use_hal_polling="0"

	hal_polling_device="/dev/cdrom"

# cdrom hal polling settings

# systemd services settings

use_systemd="0"

	use_laptop_mode_tools="0" # depends of laptop-mode-tools package

		ac_laptop_mode="0" # ATTENTION! You should change it on your own

		battery_laptop_mode="5" # ATTENTION! You should change it on your own

	use_cpufreqd="0" # depends of cpufreqd package

	use_samsung_tools="0" # depends of samsung-tools package

		oneshot_samsung_tools="0"

		daemon_samsung_tools="0"

	use_autosuspend="0"

		path_battery_percentage="/sys/class/power_supply/BAT1/capacity" # ATTENTION! You should change it on your own

		min_battery_percentage="0" # ATTENTION! You should change it on your own

	stop_setvtrgb="0"

	stop_rclocal="0"

	stop_colord="0"

	stop_keyboardsetup="0"

	stop_preload="0" # depends of preload package

	stop_avahidaemon="0"

# systemd services settings

########################################################
#                                                      #
# Here is end point preload and settings block of code #
#                                                      #
########################################################

#############################################
#                                           #
# Here is start point oneshot block of code #
#                                           #
#############################################

if on_ac_power;

then

	##############################################
	#                                            #
	# Here is start point block of code if on AC #
	#                                            #
	##############################################

	# start changing ac brightness #

	if [ $use_changing_brightness = "1" ] && [ $oneshot_brightness = "1" ]

		then

			if (( $(cat $path_brightness) < $ac_brightness ))

				then

					echo $ac_brightness > $path_brightness

				else

					$skip

			fi

		else

			$skip

	fi

	# stop changing ac brightness #

	# start unblock wifi using rfkill #

	if [ $use_rfkill = "1" ] && [ $use_changing_wifi = "1" ] && [ $oneshot_wifi = "1" ]

		then

			if (( $(rfkill list wifi | grep -c "yes") > "0" ))

				then

					sudo rfkill unblock wifi

				else

					$skip

			fi

		else

			$skip

	fi

	# stop unblock wifi using rfkill #

	# start unblock bluetooth using rfkill #

	if [ $use_rfkill = "1" ] && [ $use_changing_bluetooth = "1" ] && [ $oneshot_bluetooth = "1" ]

		then

			if (( $(rfkill list bluetooth | grep -c "yes") > "0" ))

				then

					sudo rfkill unblock bluetooth

				else

					$skip

			fi

		else

			$skip

	fi

	# stop unblock bluetooth using rfkill #

	# start you can put something here #

	if [ $use_systemd = "1" ]

		then

			$skip

		else

			$skip

	fi

	# end you can put something here #

	############################################
	#                                          #
	# Here is end point block of code if on AC #
	#                                          #
	############################################

else

	###################################################
	#                                                 #
	# Here is start point block of code if on Battery #
	#                                                 #
	###################################################

	# start changing battery brightness #

	if [ $use_changing_brightness = "1" ] && [ $oneshot_brightness = "1" ]

		then

			if (( $(cat $path_brightness) > $battery_brightness ))

				then

					echo $battery_brightness > $path_brightness

				else

					$skip

			fi

		else

			$skip

	fi

	# stop changing battery brightness #

	# start block wifi using rfkill #

	if [ $use_rfkill = "1" ] && [ $use_changing_wifi = "1" ] && [ $oneshot_wifi = "1" ]

		then

			if (( $(rfkill list wifi | grep -c "no") > "0" ))

				then

					sudo rfkill block wifi

				else

					$skip

			fi

		else

			$skip

	fi

	# stop block wifi using rfkill #

	# start block bluetooth using rfkill #

	if [ $use_rfkill = "1" ] && [ $use_changing_bluetooth = "1" ] && [ $oneshot_bluetooth = "1" ]

		then

			if (( $(rfkill list bluetooth | grep -c "no") > "0" ))

				then

					sudo rfkill block bluetooth

				else

					$skip

			fi

		else

			$skip

	fi

	# stop block bluetooth using rfkill #

	if [ $use_systemd = "1" ]

		then

			# start samsung-tools service #

			if [ $use_samsung_tools = "1" ] && [ $oneshot_samsung_tools = "1" ]

				then

					if [[ $(systemctl status samsung-tools.service | grep -c disabled) != "1" ]]

						then

							sudo systemctl disable samsung-tools.service

						else

							$skip

					fi

					if [[ $(systemctl status samsung-tools.service | grep -c inactive) = "1" ]]

						then

							sudo systemctl start samsung-tools.service

						else

							$skip

					fi

				else

					$skip

			fi

			# end of start samsung-tools service #

		else

			$skip

	fi

	#################################################
	#                                               #
	# Here is end point block of code if on Battery #
	#                                               #
	#################################################

fi

###########################################
#                                         #
# Here is end point oneshot block of code #
#                                         #
###########################################

#################################
#                               #
# Here is start point of daemon #
#                               #
#################################

while [ $loop = "1" ]

do

	#######################################################
	#                                                     #
	# Here is start point of pre-anywayshot block of code #
	#                                                     #
	#######################################################	

	if [ $use_systemd = "1" ]

		then

			# start use cpufreqd #

			if [ $use_cpufreqd = "1" ]

				then

					if [[ $(systemctl status cpufreqd.service | grep -c disabled) != "1" ]]

						then

							sudo systemctl disable cpufreqd.service

						else

							$skip

					fi

					if [[ $(systemctl status cpufreqd.service | grep -c inactive) = "1" ]]

						then

							sudo systemctl start cpufreqd.service

						else

							$skip

					fi

					if [[ $(systemctl status cpufreqd.service | grep -c inactive) != "1" ]]

						then

							sudo systemctl stop cpufreqd.service

						else

							$skip

					fi

				else

					$skip

			fi

			# stop use cpufreqd #

			# stop rc-local service #

			if [ $stop_rclocal = "1" ] && [ $(systemctl status rc-local.service | grep -c inactive) != "1" ]

				then

					sudo systemctl stop rc-local.service

				else

					$skip

			fi

			# end of stop rc-local service #

			# stop avahi-daemon service #

			if [ $stop_avahidaemon = "1" ] && [ $(systemctl status avahi-daemon.service | grep -c inactive) != "1" ]

				then

					sudo systemctl stop avahi-daemon.service

				else

					$skip

			fi

			# end of stop avahi-daemon service #

			# stop avahi-daemon socket #

			if [ $stop_avahidaemon = "1" ] && [ $(systemctl status avahi-daemon.socket | grep -c inactive) != "1" ]

				then

					sudo systemctl stop avahi-daemon.socket

				else

					$skip

			fi

			# end of stop avahi-daemon socket #

			# stop keyboard-setup service #

			if [ $stop_keyboardsetup = "1" ] && [ $(systemctl status keyboard-setup.service | grep -c inactive) != "1" ]

				then

					sudo systemctl stop keyboard-setup.service

				else

					$skip

			fi

			# end of stop keyboard-setup service #

			# start use laptop-mode tools

			if [ $use_laptop_mode_tools = "1" ]

				then

					if [[ $(systemctl status laptop-mode.timer | grep -c disabled) != "1" ]]

						then

							sudo systemctl disable laptop-mode.timer

						else

							$skip

					fi

					if [[ $(systemctl status laptop-mode.service | grep -c "disabled;") != "1" ]]

						then

							sudo systemctl disable laptop-mode.service

						else

							$skip

					fi

					if [[ $(systemctl status lmt-poll.service | grep -c disabled) != "1" ]]

						then

							sudo systemctl disable lmt-poll.service

						else

							$skip

					fi

					if [[ $(systemctl status laptop-mode.timer | grep -c inactive) = "1" ]]

						then

							sudo systemctl start laptop-mode.timer

						else

							$skip

					fi

					if [[ $(systemctl status laptop-mode.service | grep -c inactive) = "1" ]]

						then

							sudo systemctl start laptop-mode.service

						else

							$skip

					fi

					if [[ $(systemctl status lmt-poll.service | grep -c inactive) = "1" ]]

						then

							sudo systemctl start lmt-poll.service

						else

							$skip

					fi

					if on_ac_power;

						then

							if (( $(cat /proc/sys/vm/laptop_mode) != $ac_laptop_mode ))

								then

									echo $ac_laptop_mode > /proc/sys/vm/laptop_mode

								else

									$skip

							fi

						else

							if (( $(cat /proc/sys/vm/laptop_mode) != $battery_laptop_mode ))

								then

									echo $battery_laptop_mode > /proc/sys/vm/laptop_mode

								else

									$skip

							fi

					fi

					if [[ $(systemctl status laptop-mode.timer | grep -c inactive) != "1" ]]

						then

							sudo systemctl restart laptop-mode.timer

						else

							$skip

					fi

					if [[ $(systemctl status laptop-mode.service | grep -c inactive) != "1" ]]

						then

							sudo systemctl restart laptop-mode.service

						else

							$skip

					fi

					if [[ $(systemctl status lmt-poll.service | grep -c inactive) != "1" ]]

						then

							sudo systemctl restart lmt-poll.service

						else

							$skip

					fi

					if [[ $(systemctl status laptop-mode.service | grep -c inactive) != "1" ]]

						then

							sudo systemctl reload laptop-mode.service

						else

							$skip

					fi

					if [[ $(systemctl status laptop-mode.timer | grep -c inactive) != "1" ]]

						then

							sudo systemctl stop laptop-mode.timer

						else

							$skip

					fi

					if [[ $(systemctl status lmt-poll.service | grep -c inactive) != "1" ]]

						then

							sudo systemctl stop lmt-poll.service

						else

							$skip

					fi

					if [[ $(systemctl status laptop-mode.service | grep -c inactive) != "1" ]]

						then

							sudo systemctl stop laptop-mode.service

						else

							$skip

					fi

				else

					$skip

			fi

			# stop use laptop-mode-tools

		else

			$skip

	fi

	#####################################################
	#                                                   #
	# Here is end point of pre-anywayshot block of code #
	#                                                   #
	#####################################################

	if on_ac_power;

	then

		##############################################
		#                                            #
		# Here is start point block of code if on AC #
		#                                            #
		##############################################

		# start of use performance tray indicator

		if [ $use_gtrayicon = "1" ]

			then

				if [[ $(pgrep -f -c "GLPS-Daemon: performance") != "0" ]] && [[ $(pgrep -f -c "GLPS-Daemon: powersave") = "0" ]]

					then

						$skip 

					else

						if [[ $(pgrep -f -c "GLPS-Daemon: powersave") != "0" ]]

							then

								kill $(pgrep -f "GLPS-Daemon: powersave")
					
							else

								$skip

						fi

						if [[ $(pgrep -f -c "GLPS-Daemon: performance") != "0" ]]

							then

								$skip

							else

								export DISPLAY=:0

								export DISPLAY=:0.0

								su $(who -q | grep -v =) -c 'DISPLAY=:0.0 gtrayicon --display=:0.0 --activate='' --deactivate='' --activate-icon=/usr/share/icons/gnome/scalable/emotes/face-devilish-symbolic.svg --deactivate-icon=/usr/share/icons/gnome/scalable/emotes/face-devilish-symbolic.svg --tooltip="GLPS-Daemon: performance" > /dev/null 2>&1 &'

								if [ $use_notify_send = "1" ] && [ $use_notify_send_with_gtrayicon = "1" ]

									then

										export DISPLAY=:0

										export DISPLAY=:0.0

										su $(who -q | grep -v =) -c 'DISPLAY=:0.0 notify-send -i daemon "GPLS-Daemon" "Set performance settings"'

									else

										$skip

								fi

						fi

				fi

			else

				$skip

		fi

		# end of use performance tray indicator

		# start of performance notification send

		if [ $use_notify_send = "1" ] && [ $use_notify_send_standalone = "1" ]

			then

				export DISPLAY=:0

				export DISPLAY=:0.0

				su $(who -q | grep -v =) -c 'DISPLAY=:0.0 notify-send -i daemon "GPLS-Daemon" "Set performance settings"'

			else

				$skip

		fi

		# end of performance notification send

		# start changing laptop-mode setting #

		if [ $use_laptop_mode_tools = "1" ]

			then

				if (( $(cat /proc/sys/vm/laptop_mode) != $ac_laptop_mode ))

					then

						echo $ac_laptop_mode > /proc/sys/vm/laptop_mode

					else

						$skip

				fi

			else

				$skip

		fi

		# stop changing laptop-mode setting #

		# start changing kernel params for ac #

		if [ $use_changing_kernel_params = "1" ]

			then

				if (( $(cat /proc/sys/vm/dirty_ratio) != 10 ))

					then

						echo 10 > /proc/sys/vm/dirty_ratio

					else

						$skip

				fi

				if (( $(cat /proc/sys/vm/dirty_background_ratio) != 5 ))

					then

						echo 5 > /proc/sys/vm/dirty_background_ratio

					else

						$skip

				fi

				if (( $(cat /proc/sys/vm/dirty_expire_centisecs) != 1000 ))

					then

						echo 1000 > /proc/sys/vm/dirty_expire_centisecs

					else

						$skip

				fi

				if (( $(cat /proc/sys/vm/dirty_writeback_centisecs) != 1000 ))

					then

						echo 1000 > /proc/sys/vm/dirty_writeback_centisecs

					else

						$skip

				fi

				if (( $(cat /sys/module/snd_hda_intel/parameters/power_save) != 0 ))

					then

						echo 0 > /sys/module/snd_hda_intel/parameters/power_save

					else

						$skip

				fi

			else

				$skip

		fi

		# stop changing kernel params for ac #

		# start changing ac brightness #

		if [ $use_changing_brightness = "1" ] && [ $daemon_brightness = "1" ]

			then

				if (( $(cat $path_brightness) < $ac_brightness ))

					then

						echo $ac_brightness > $path_brightness

					else

						$skip

				fi

			else

				$skip

		fi

		# stop changing ac brightness #

		# start enable camera with modprobe #

		if [ $use_modprobe = "1" ]

			then

				if [ $use_changing_camera = "1" ] && [ $(ls /dev/ | grep -c "video") = "0" ]

					then

						sudo modprobe uvcvideo

					else

						$skip

				fi

			else

				$skip

		fi

		# stop enable camera with modprobe #

		# disable mc power saving #

		if [ $use_mc_power_saving = "1" ]

			then

				if [[ $(cat /sys/devices/system/cpu/sched_mc_power_savings) != "0" ]]

					then

						echo 0 > /sys/devices/system/cpu/sched_mc_power_savings

					else

						$skip

				fi

			else

				$skip

		fi

		# end of disable mc power saving #

		# disable smt power saving #

		if [ $use_smt_power_saving = "1" ]

			then

				if [[ $(cat /sys/devices/system/cpu/sched_smt_power_savings) != "0" ]]

					then

						echo 0 > /sys/devices/system/cpu/sched_smt_power_savings

					else

						$skip

				fi

			else

				$skip

		fi

		# end of disable smt power saving #

		if [ $use_wireless_powersaving = "1" ]

			then

				# disable power management in iw dev #

				if [ $use_iw_pm = "1" ]

					then

						if (( $(iw dev $wireless_interface get power_save | grep -c "off") != 1 ))

							then

								sudo iw dev $wireless_interface set power_save off

							else

								$skip

						fi

					else

						$skip

				fi

				if [ $use_iw_txpower = "1" ] && (( $(sudo iwlist $wireless_interface txpower | grep -c "Tx-Power:off") != "1" ))

					then

						if (( $(sudo iwlist $wireless_interface txpower | grep -c "Tx-Power=$iw_default_txpower") != "1" ))

							then

								sudo iw dev $wireless_interface set txpower $iw_set_default_txpower

							else

								$skip

						fi

					else

						$skip

				fi

				# end of disable power management in iw dev #

				# disable power management in iwconfig #

				if [ $use_iwconfig_pm = "1" ]

					then

						if (( $(iwconfig $wireless_interface | grep -c "Power Management:off") != 1 ))

							then

								sudo iwconfig $wireless_interface power off

							else

								$skip

						fi

					else

						$skip

				fi

				if [ $use_iwconfig_txpower = "1" ] && (( $(sudo iwconfig $wireless_interface | grep -c "Tx-Power=off") != "1" ))

					then

						if (( $(sudo iwconfig $wireless_interface | grep -c "Tx-Power=$iwconfig_default_txpower") != "1" ))

							then

								sudo iwconfig $wireless_interface txpower $iwconfig_set_default_txpower

							else

								$skip

						fi

					else

						$skip

				fi

				# end of disable power management in iwconfig #

			else

				$skip

		fi

		# start enabling ipv6 #

		if [ $use_changing_ipv6 = "1" ]

			then

				if (( $(cat /proc/sys/net/ipv6/conf/all/disable_ipv6) != 0 ))

					then

						echo 0 > /proc/sys/net/ipv6/conf/all/disable_ipv6

					else

						$skip

				fi

				if [ $use_sysctl = "1" ]

					then

						if (( $(sysctl net.ipv6.conf.all.disable_ipv6 | grep -c "1") != 0 ))

							then

								sudo sysctl -w net.ipv6.conf.all.disable_ipv6=0

							else

								$skip

						fi

						if (( $(sysctl net.ipv6.conf.default.disable_ipv6 | grep -c "1") != 0 ))

							then

								sudo sysctl -w net.ipv6.conf.default.disable_ipv6=0

							else

								$skip

						fi

						if (( $(sysctl net.ipv6.conf.lo.disable_ipv6 | grep -c "1") != 0 ))

							then

								sudo sysctl -w net.ipv6.conf.lo.disable_ipv6=0

							else

								$skip

						fi

						if (( $(sysctl net.ipv6.conf.$wireless_interface.disable_ipv6 | grep -c "1") != 0 ))

							then

								sudo sysctl -w net.ipv6.conf.$wireless_interface.disable_ipv6=0

							else

								$skip

						fi

					else

						$skip

				fi

			else

				$skip

		fi

		# stop enabling ipv6 #

		# start changing scsi ac power #

		if [ $use_changing_scsi = "1" ]

			then

				for (( s = 0; s < $number_of_scsi_host; s++ ))

				do

					if [ $(cat /sys/class/scsi_host/host$s/link_power_management_policy) != $ac_scsi_host ]

						then

							echo $ac_scsi_host > /sys/class/scsi_host/host$s/link_power_management_policy

						else

							$skip

					fi

				done

			else

				$skip

		fi

		# stop changing scsi ac power #

		# start changing ac governor #

		if [ $use_changing_governor = "1" ]

			then

				for (( c = 0; c < $number_of_cores; c++ ))

				do

					if [ $(cat /sys/devices/system/cpu/cpu$c/cpufreq/scaling_governor) != $ac_governor ]

						then

							echo $ac_governor > /sys/devices/system/cpu/cpu$c/cpufreq/scaling_governor

						else

							$skip

					fi

				done

			else

				$skip

		fi

		# stop changing ac governor #

		# start changing ac governor in cpufreq-set #

		if [ $use_changing_governor = "1" ] && [ $use_cpufreq = "1" ]

			then

				for (( c = 0; c < $number_of_cores; c++ ))

				do

					if [ $(cat /sys/devices/system/cpu/cpu$c/cpufreq/scaling_governor) != $ac_governor ]

						then

							sudo cpufreq-set -c $c -g $ac_governor

						else

							$skip

					fi

				done

			else

				$skip

		fi

		# stop changing ac governor in cpufreq-set #

		# start changing pcie aspm policy on ac #

		if [ $use_changing_pcie = "1" ]

			then

				if (( $(cat /sys/module/pcie_aspm/parameters/policy | grep -c "performance") != "1" ))

					then

						echo performance > /sys/module/pcie_aspm/parameters/policy

					else

						$skip

				fi

			else

				$skip

		fi

		# stop changing pcie aspm policy on ac #

		# start enable hal polling on device (experimental function) #

		if [ $use_hal_polling = "1" ]

			then

				sudo hal-disable-polling --enable-polling --device $hal_polling_device

			else

				$skip

		fi

		# stop enable hal polling on device (experimental function) #

		# start unblock wifi using rfkill #

		if [ $use_rfkill = "1" ] && [ $use_changing_wifi = "1" ] && [ $daemon_wifi = "1" ]

			then

				if (( $(rfkill list wifi | grep -c "yes") > "0" ))

					then

						sudo rfkill unblock wifi

					else

						$skip

				fi

			else

				$skip

		fi

		# stop unblock wifi using rfkill #

		# start unblock bluetooth using rfkill #

		if [ $use_rfkill = "1" ] && [ $use_changing_bluetooth = "1" ] && [ $daemon_bluetooth = "1" ]

			then

				if (( $(rfkill list bluetooth | grep -c "yes") > "0" ))

					then

						sudo rfkill unblock bluetooth

					else

						$skip

				fi

			else

				$skip

		fi

		# stop unblock bluetooth using rfkill #

		# start disable power saving with hdparm #

		if [ $use_hdparm = "1" ]

			then

				if (( $(sudo hdparm -B $hard_disk | grep -c "= off") != "1" ))

					then

						sudo hdparm -B 255 $hard_disk

					else

						$skip

				fi

				if (( $(sudo hdparm -M $hard_disk | grep -c "= 254") != "1" ))

					then

						sudo hdparm -M 254 $hard_disk

					else

						$skip

				fi

				if (( $(sudo hdparm -W $hard_disk | grep -c "on") != "1" ))

					then

						sudo hdparm -W 1 $hard_disk

					else

						$skip

				fi

				if (( $(sudo hdparm -C $hard_disk | grep -c "active/idle") != "1" )) || (( $(sudo hdparm -C $hard_disk | grep -c "standby") != "1" ))

					then

						sudo hdparm -S 0 $hard_disk

					else

						$skip

				fi

			else

				$skip

		fi

		# stop disable power saving with hdparm #

		############################################
		#                                          #
		# Here is end point block of code if on AC #
		#                                          #
		############################################

	else

		###################################################
		#                                                 #
		# Here is start point block of code if on Battery #
		#                                                 #
		###################################################

		# start of autosuspend feature if battery percentage less than your minimum #

		if [ $use_systemd = "1" ] && [ $use_autosuspend = "1" ] && (( $(cat $path_battery_percentage) < $min_battery_percentage ))

		then

			sudo systemctl suspend

		else

		# end of autosuspend feature if battery percentage less than your minimum #

			# start use powersave gtrayicon

			if [ $use_gtrayicon = "1" ]

				then

					if [[ $(pgrep -f -c "GLPS-Daemon: powersave") != "0" ]] && [[ $(pgrep -f -c "GLPS-Daemon: performance") = "0" ]]

						then

							$skip 

						else

							if [[ $(pgrep -f -c "GLPS-Daemon: performance") != "0" ]]

								then

									kill $(pgrep -f "GLPS-Daemon: performance")
							
								else

									$skip

							fi

							if [[ $(pgrep -f -c "GLPS-Daemon: powersave") != "0" ]]

								then

									$skip

								else

									export DISPLAY=:0

									export DISPLAY=:0.0

									su $(who -q | grep -v =) -c 'DISPLAY=:0.0 gtrayicon --display=:0.0 --activate='' --deactivate='' --activate-icon=/usr/share/icons/gnome/scalable/emotes/face-devilish-symbolic.svg --deactivate-icon=/usr/share/icons/gnome/scalable/emotes/face-devilish-symbolic.svg --tooltip="GLPS-Daemon: powersave" > /dev/null 2>&1 &'

									if [ $use_notify_send = "1" ] && [ $use_notify_send_with_gtrayicon = "1" ]

										then

											export DISPLAY=:0

											export DISPLAY=:0.0

											su $(who -q | grep -v =) -c 'DISPLAY=:0.0 notify-send -i daemon "GPLS-Daemon" "Set powersave settings"'

										else

											$skip

									fi

							fi

					fi

				else

					$skip

			fi

			# end use powersave gtrayicon

			# start of powersave notification send

			if [ $use_notify_send = "1" ] && [ $use_notify_send_standalone = "1" ]

				then

					export DISPLAY=:0

					export DISPLAY=:0.0

					su $(who -q | grep -v =) -c 'DISPLAY=:0.0 notify-send -i daemon "GPLS-Daemon" "Set powersave settings"'

				else

					$skip

			fi

			# end of powersave notification send

			# start samsung-tools service #

			if [ $use_samsung_tools = "1" ] && [ $daemon_samsung_tools = "1" ]

				then

					if [[ $(systemctl status samsung-tools.service | grep -c disabled) != "1" ]]

						then

							sudo systemctl disable samsung-tools.service

						else

							$skip

					fi

					if [[ $(systemctl status samsung-tools.service | grep -c inactive) = "1" ]]

						then

							sudo systemctl start samsung-tools.service

						else

							$skip

					fi

					if [[ $(systemctl status samsung-tools.service | grep -c inactive) != "1" ]]

						then

							sudo systemctl stop samsung-tools.service

						else

							$skip

					fi

				else

					$skip

			fi

			# end of start samsung-tools service #

			# start use powertop #

			if [ $use_powertop = "1" ]

				then

					sudo powertop -q --auto-tune

				else

					$skip

			fi

			# stop use powertop #

			# start changing laptop-mode setting #

			if [ $use_laptop_mode_tools = "1" ]

				then

					if (( $(cat /proc/sys/vm/laptop_mode) != $battery_laptop_mode ))

						then

							echo $battery_laptop_mode > /proc/sys/vm/laptop_mode

						else

							$skip

					fi

				else

					$skip

			fi

			# stop changing laptop-mode setting #

			# start changing kernel params for ac #

			if [ $use_changing_kernel_params = "1" ]

				then

					if (( $(cat /proc/sys/vm/dirty_ratio) != 90 ))

						then

							echo 90 > /proc/sys/vm/dirty_ratio

						else

							$skip

					fi

					if (( $(cat /proc/sys/vm/dirty_background_ratio) != 1 ))

						then

							echo 1 > /proc/sys/vm/dirty_background_ratio

						else

							$skip

					fi

					if (( $(cat /proc/sys/vm/dirty_expire_centisecs) != 60000 ))

						then

							echo 60000 > /proc/sys/vm/dirty_expire_centisecs

						else

							$skip

					fi

					if (( $(cat /proc/sys/vm/dirty_writeback_centisecs) != 60000 ))

						then

							echo 60000 > /proc/sys/vm/dirty_writeback_centisecs

						else

							$skip

					fi

					if (( $(cat /sys/module/snd_hda_intel/parameters/power_save) != 1 ))

						then

							echo 1 > /sys/module/snd_hda_intel/parameters/power_save

						else

							$skip

					fi

				else

					$skip

			fi

			# stop changing kernel params for ac #

			# start changing battery brightness #

			if [ $use_changing_brightness = "1" ] && [ $daemon_brightness = "1" ]

				then

					if (( $(cat $path_brightness) > $battery_brightness ))

						then

							echo $battery_brightness > $path_brightness

						else

							$skip

					fi

				else

					$skip

			fi

			# stop changing battery brightness #

			# start disable camera with modprobe #

			if [ $use_modprobe = "1" ]

				then

					if [ $use_changing_camera = "1" ] && [ $(ls /dev/ | grep -c "video") != 0 ]

						then

							sudo modprobe -r uvcvideo

						else

							$skip

					fi

				else

					$skip

			fi

			# stop disable camera with modprobe #

			# enable mc power saving #

			if [ $use_mc_power_saving = "1" ]

				then

					if [[ $(cat /sys/devices/system/cpu/sched_mc_power_savings) != "1" ]]

						then

							echo 1 > /sys/devices/system/cpu/sched_mc_power_savings

						else

							$skip

					fi

				else

					$skip

			fi

			# end of enable mc power saving #

			# enable smt power saving #

			if [ $use_smt_power_saving = "1" ]

				then

					if [[ $(cat /sys/devices/system/cpu/sched_smt_power_savings) != "1" ]]

						then

							echo 1 > /sys/devices/system/cpu/sched_smt_power_savings

						else

							$skip

					fi

				else

					$skip

			fi

			# end of enable smt power saving #

			if [ $use_wireless_powersaving = "1" ]

				then

					# enable power management in iw dev #

					if [ $use_iw_pm = "1" ]

						then

							if (( $(iw dev $wireless_interface get power_save | grep -c "on") != 1 ))

								then

									sudo iw dev $wireless_interface set power_save on

								else

									$skip

							fi

						else

							$skip

					fi

					if [ $use_iw_txpower = "1" ] && (( $(sudo iwlist $wireless_interface txpower | grep -c "Tx-Power:off") != "1" ))

						then

							if (( $(sudo iwlist $wireless_interface txpower | grep -c "Tx-Power=$iw_powersave_txpower") != "1" ))

								then

									sudo iw dev $wireless_interface set txpower $iw_set_powersave_txpower

								else

									$skip

							fi

						else

							$skip

					fi

					# end of enable power management in iw dev #

					# enable power management in iwconfig #

					if [ $use_iwconfig_pm = "1" ]

						then

							if (( $(iwconfig $wireless_interface | grep -c "Power Management:on") != 1 ))

								then

									sudo iwconfig $wireless_interface power on

								else

									$skip

							fi

						else

							$skip

					fi

					if [ $use_iwconfig_txpower = "1" ] && (( $(sudo iwconfig $wireless_interface | grep -c "Tx-Power=off") != "1" ))

						then

							if (( $(sudo iwconfig $wireless_interface | grep -c "Tx-Power=$iwconfig_powersave_txpower") != "1" ))

								then

									sudo iwconfig $wireless_interface txpower $iwconfig_set_powersave_txpower

								else

									$skip

							fi

						else

							$skip

					fi

					# end of enable power management in iwconfig #

				else

					$skip

			fi

			# start disabling ipv6 #

			if [ $use_changing_ipv6 = "1" ]

				then

					if (( $(cat /proc/sys/net/ipv6/conf/all/disable_ipv6) != 1 ))

						then

							echo 1 > /proc/sys/net/ipv6/conf/all/disable_ipv6

						else

							$skip

					fi

					if [ $use_sysctl = "1" ]

						then

							if (( $(sysctl net.ipv6.conf.all.disable_ipv6 | grep -c "1") != 1 ))

								then

									sudo sysctl -w net.ipv6.conf.all.disable_ipv6=1

								else

									$skip

							fi

							if (( $(sysctl net.ipv6.conf.default.disable_ipv6 | grep -c "1") != 1 ))

								then

									sudo sysctl -w net.ipv6.conf.default.disable_ipv6=1

								else

									$skip

							fi

							if (( $(sysctl net.ipv6.conf.lo.disable_ipv6 | grep -c "1") != 1 ))

								then

									sudo sysctl -w net.ipv6.conf.lo.disable_ipv6=1

								else

									$skip

							fi

							if (( $(sysctl net.ipv6.conf.$wireless_interface.disable_ipv6 | grep -c "1") != 1 ))

								then

									sudo sysctl -w net.ipv6.conf.$wireless_interface.disable_ipv6=1

								else

									$skip

							fi

						else

							$skip

					fi

				else

					$skip

			fi

			# stop disabling ipv6 #

			# start changing scsi battery power #

			if [ $use_changing_scsi = "1" ]

				then

					for (( s = 0; s < $number_of_scsi_host; s++ ))

					do

						if [ $(cat /sys/class/scsi_host/host$s/link_power_management_policy) != $battery_scsi_host ]

							then

								echo $battery_scsi_host > /sys/class/scsi_host/host$s/link_power_management_policy

							else

								$skip

						fi

					done

				else

					$skip

			fi

			# stop changing scsi battery power #

			# start changing battery governor #

			if [ $use_changing_governor = "1" ]

				then

					for (( c = 0; c < $number_of_cores; c++ ))

					do

						if [ $(cat /sys/devices/system/cpu/cpu$c/cpufreq/scaling_governor) != $battery_governor ]

							then

								echo $battery_governor > /sys/devices/system/cpu/cpu$c/cpufreq/scaling_governor

							else

								$skip

						fi

					done

				else

					$skip

			fi

			# stop changing battery governor #

			# start changing battery governor in cpufreq-set #

			if [ $use_changing_governor = "1" ] && [ $use_cpufreq = "1" ]

				then

					for (( c = 0; c < $number_of_cores; c++ ))

					do

						if [ $(cat /sys/devices/system/cpu/cpu$c/cpufreq/scaling_governor) != $battery_governor ]

							then

								sudo cpufreq-set -c $c -g $battery_governor

							else

								$skip

						fi

					done

				else

					$skip

			fi

			# stop changing battery governor in cpufreq-set #

			# start changing pcie aspm policy on battery #

			if [ $use_changing_pcie = "1" ]

				then

					if (( $(cat /sys/module/pcie_aspm/parameters/policy | grep -c "powersave") != "1" ))

						then

							echo powersave > /sys/module/pcie_aspm/parameters/policy

						else

							$skip

					fi

				else

					$skip

			fi

			# stop changing pcie aspm policy on battery #

			# start disable hal polling on device (experimental function) #

			if [ $use_hal_polling = "1" ]

				then

					sudo hal-disable-polling --device $hal_polling_device

				else

					$skip

			fi

			# stop disable hal polling on device (experimental function) #

			# start block wifi using rfkill #

			if [ $use_rfkill = "1" ] && [ $use_changing_wifi = "1" ] && [ $daemon_wifi = "1" ]

				then

					if (( $(rfkill list wifi | grep -c "no") > "0" ))

						then

							sudo rfkill block wifi

						else

							$skip

					fi

				else

					$skip

			fi

			# stop block wifi using rfkill #

			# start block bluetooth using rfkill #

			if [ $use_rfkill = "1" ] && [ $use_changing_bluetooth = "1" ] && [ $daemon_bluetooth = "1" ]

				then

					if (( $(rfkill list bluetooth | grep -c "no") > "0" ))

						then

							sudo rfkill block bluetooth

						else

							$skip

					fi

				else

					$skip

			fi

			# stop block bluetooth using rfkill #

			# start setting power saving with hdparm #

			if [ $use_hdparm = "1" ]

				then

					if (( $(sudo hdparm -B $hard_disk | grep -c "= 1") != "1" ))

						then

							sudo hdparm -B 1 $hard_disk

						else

							$skip

					fi

					if (( $(sudo hdparm -M $hard_disk | grep -c "= 128") != "1" ))

						then

							sudo hdparm -M 128 $hard_disk

						else

							$skip

					fi

					if (( $(sudo hdparm -W $hard_disk | grep -c "off") != "1" ))

						then

							sudo hdparm -W 0 $hard_disk

						else

							$skip

					fi

					if (( $(sudo hdparm -C $hard_disk | grep -c "standby") != "1" ))

						then

							sudo hdparm -S 1 $hard_disk

						else

							$skip

					fi

				else

					$skip

			fi

			# stop setting power saving with hdparm #

		fi

		#################################################
		#                                               #
		# Here is end point block of code if on Battery #
		#                                               #
		#################################################

	fi

	########################################################
	#                                                      #
	# Here is start point of post-anywayshot block of code #
	#                                                      #
	########################################################

	$longwait

	if [ $use_systemd = "1" ]

		then

			# stop setvtrgb service #

			if [ $stop_setvtrgb = "1" ] && [ $(systemctl status setvtrgb.service | grep -c inactive) != "1" ]

				then

					sudo systemctl stop setvtrgb.service

				else

					$skip

			fi

			# end of stop setvtrgb service #

			# stop colord service #

			if [ $stop_colord = "1" ] && [ $(systemctl status colord.service | grep -c inactive) != "1" ]

				then

					sudo systemctl stop colord.service

				else

					$skip

			fi

			# end of stop colord service #

			# stop preload service #

			if [ $stop_preload = "1" ] && [ $(systemctl status preload.service | grep -c inactive) != "1" ]

				then

					sudo systemctl stop preload.service

				else

					$skip

			fi

			# end of stop preload service #

		else

			$skip

	fi

	######################################################
	#                                                    #
	# Here is end point of post-anywayshot block of code #
	#                                                    #
	######################################################

done

###############################
#                             #
# Here is end point of daemon #
#                             #
###############################

